version: "3"

services:
  db:
    image: mongo:5
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGODB_DATABASE: venda-livros
    volumes:
      - ./mongo:/data/db
  zipkin:
    image: openzipkin/zipkin:2
    ports:
      - '9411:9411'